In [1]:
import pandas as pd

In [4]:
FBI_df = "../output_files/FBI.csv"
Agencies_df= "../output_files/agencies.csv"

In [5]:
FBI_df = pd.read_csv(FBI_df, encoding="ISO-8859-1")
Agencies_df= pd.read_csv(Agencies_df, encoding="ISO-8859-1")

In [21]:
FBI_df.head()

,Unnamed: 0,actual,cleared,data_year,offense,ori,state_abbr
0,0,13,5,2017,aggravated-assault,NJ0012100,NJ
1,1,2,2,2017,aggravated-assault,NJ0012200,NJ
2,2,0,0,2017,aggravated-assault,NJ0012400,NJ
3,3,28,11,2017,aggravated-assault,NJ001SP00,NJ
4,4,3,2,2017,aggravated-assault,NJ0020000,NJ

In [22]:
Agencies_df.head()

   Unnamed: 0                            agency_name county_name        ori
0           0              Bayonne Police Department      HUDSON  NJ0090100
1           1               Orange Police Department       ESSEX  NJ0071700
2           2  Long Beach Township Police Department       OCEAN  NJ0151700
3           3         Midland Park Police Department      BERGEN  NJ0023500
4           4         Saddle River Police Department      BERGEN  NJ0025800

In [24]:
merged_df= pd.merge(FBI_df, Agencies_df, on="ori",how="left")
merged_df.head()

,Unnamed: 0_x,actual,cleared,data_year,offense,ori,state_abbr,Unnamed: 0_y,agency_name,county_name
0,0,13,5,2017,aggravated-assault,NJ0012100,NJ,471,Somers Point Police Department,ATLANTIC
1,1,2,2,2017,aggravated-assault,NJ0012200,NJ,504,Ventnor City Police Department,ATLANTIC
2,2,0,0,2017,aggravated-assault,NJ0012400,NJ,571,Stockton University,ATLANTIC
3,3,28,11,2017,aggravated-assault,NJ001SP00,NJ,347,State Police: Atlantic County,ATLANTIC
4,4,3,2,2017,aggravated-assault,NJ0020000,NJ,25,Bergen County Sheriff's Office,BERGEN

In [30]:
crime_df= merged_df.drop(columns=['Unnamed: 0_x', 'Unnamed: 0_y', 'state_abbr'])

In [31]:
#Changing county names from upper case to title case to reference with demography data
crime_df['county_name'] = crime_df['county_name'].str.title() 
crime_df.head()

,actual,cleared,data_year,offense,ori,agency_name,county_name
0,13,5,2017,aggravated-assault,NJ0012100,Somers Point Police Department,Atlantic
1,2,2,2017,aggravated-assault,NJ0012200,Ventnor City Police Department,Atlantic
2,0,0,2017,aggravated-assault,NJ0012400,Stockton University,Atlantic
3,28,11,2017,aggravated-assault,NJ001SP00,State Police: Atlantic County,Atlantic
4,3,2,2017,aggravated-assault,NJ0020000,Bergen County Sheriff's Office,Bergen

In [32]:
crime_df= crime_df.rename(columns={"ori": "ORI", "county_name":"county", "actual":"cases_reported", "cleared":"cases_cleared" })
crime_df.head()

,cases_reported,cases_cleared,data_year,offense,ORI,agency_name,county
0,13,5,2017,aggravated-assault,NJ0012100,Somers Point Police Department,Atlantic
1,2,2,2017,aggravated-assault,NJ0012200,Ventnor City Police Department,Atlantic
2,0,0,2017,aggravated-assault,NJ0012400,Stockton University,Atlantic
3,28,11,2017,aggravated-assault,NJ001SP00,State Police: Atlantic County,Atlantic
4,3,2,2017,aggravated-assault,NJ0020000,Bergen County Sheriff's Office,Bergen

In [33]:
crime_df= crime_df[['county', 'agency_name', 'ORI','offense', 'cases_reported', 'cases_cleared', 'data_year' ]]
crime_df.head()

,county,agency_name,ORI,offense,cases_reported,cases_cleared,data_year
0,Atlantic,Somers Point Police Department,NJ0012100,aggravated-assault,13,5,2017
1,Atlantic,Ventnor City Police Department,NJ0012200,aggravated-assault,2,2,2017
2,Atlantic,Stockton University,NJ0012400,aggravated-assault,0,0,2017
3,Atlantic,State Police: Atlantic County,NJ001SP00,aggravated-assault,28,11,2017
4,Bergen,Bergen County Sheriff's Office,NJ0020000,aggravated-assault,3,2,2017

In [44]:
# crime_df_group=crime_df.groupby(['county', 'offense']).mean()
# crime_df_group.head(30)

                                cases_reported  cases_cleared  data_year
county     offense
Atlantic   aggravated-assault        21.618182      10.072727     2017.0
           arson                      1.400000       0.800000     2017.0
           burglary                  56.066667      10.066667     2017.0
           homicide                   1.050000       0.300000     2017.0
           larceny                  377.500000      99.900000     2017.0
           motor-vehicle-theft       15.200000       2.133333     2017.0
           property-crime           452.928571     106.500000     2017.0
           rape                       3.533333       0.400000     2017.0
           rape-legacy                0.000000       0.000000     2017.0
           robbery                    2.500000       0.500000     2017.0
           violent-crime             44.000000      14.800000     2017.0
Bergen     aggravated-assault         4.105263       3.157895     2017.0
           arson                      0.253731       0.149254     2017.0
           burglary                  17.688889       3.288889     2017.0
           homicide                   0.070423       0.070423     2017.0
           larceny                  107.657895      26.460526     2017.0
           motor-vehicle-theft        7.572816       0.864078     2017.0
           property-crime           128.376923      28.653846     2017.0
           rape                       0.676768       0.373737     2017.0
           rape-legacy                0.000000       0.000000     2017.0
           robbery                    4.589286       2.125000     2017.0
           violent-crime              9.728155       6.242718     2017.0
Burlington aggravated-assault        12.727273       6.181818     2017.0
           arson                      0.727273       0.159091     2017.0
           burglary                  41.877551       5.734694     2017.0
           homicide                   0.473684       0.157895     2017.0
           larceny                  150.400000      26.044444     2017.0
           motor-vehicle-theft       11.131579       1.605263     2017.0
           property-crime           196.346154      37.230769     2017.0
           rape                       4.156250       0.937500     2017.0

In [36]:
crime_df.to_csv("../output_files/crime.csv", index=False, header=True)